services:
  coachlab_site:
    build:
      context: .
      dockerfile: Dockerfile.php-apache
    container_name: coachlab_site
    restart: unless-stopped
    volumes:
      - ./public_html:/var/www/html
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
      - ./apache/conf/servername.conf:/etc/apache2/conf-enabled/servername.conf:ro
      - ./apache/private:/var/www/private:rw
      - ./player_data:/var/www/player_data:rw
    command: >
      sh -c "a2enmod rewrite headers alias && apache2-foreground"
    ports:
      - "8090:80"
    env_file:
      - .env
